name: 'Build master'

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Use gradle cache for faster builds
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
      - name: Clean gradle
        run: ./gradlew clean --no-daemon --max-workers 1
      - name: Build with Gradle
        run: ./gradlew build --no-daemon --max-workers 1
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
        name: failure-reports
        path: |
          **/build/reports/tests/*
      - uses: actions/upload-artifact@v2
        with:
          name: master-snapshot
          path: |
            **/build/libs/*.jar
