package io.github.appliedenergistics.metrics.fabric.network;

import com.google.common.collect.ImmutableMap;

import java.util.Map;

final class VanillaPacketTypes {

    private VanillaPacketTypes() {
    }

    /**
     * We need this map because at runtime, the classnames have been obfuscated/have
     * intermediate names. Using this map, we can get back nice names.
     *
     * <p>
     * Generate this using the {@link GenerateNicePacketNames} utility in a
     * dev-environment where names are not obfuscated.
     */
    private static final Map<Class<?>, String> VANILLA_PACKET_NAMES = ImmutableMap.<Class<?>, String>builder()
            .put(net.minecraft.network.packet.s2c.play.EntityTrackerUpdateS2CPacket.class, "entity_tracker_update")
            .put(net.minecraft.network.packet.s2c.play.TagQueryResponseS2CPacket.class, "tag_query_response")
            .put(net.minecraft.network.packet.s2c.play.ScoreboardPlayerUpdateS2CPacket.class,
                    "scoreboard_player_update")
            .put(net.minecraft.network.packet.s2c.play.PlayerActionResponseS2CPacket.class, "player_action_response")
            .put(net.minecraft.network.packet.s2c.play.BlockBreakingProgressS2CPacket.class, "block_breaking_progress")
            .put(net.minecraft.network.packet.c2s.play.KeepAliveC2SPacket.class, "keep_alive")
            .put(net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.class, "player_interact_block")
            .put(net.minecraft.network.packet.c2s.play.AdvancementTabC2SPacket.class, "advancement_tab")
            .put(net.minecraft.network.packet.c2s.play.UpdatePlayerAbilitiesC2SPacket.class, "update_player_abilities")
            .put(net.minecraft.network.packet.s2c.play.ExperienceBarUpdateS2CPacket.class, "experience_bar_update")
            .put(net.minecraft.network.packet.s2c.play.UnloadChunkS2CPacket.class, "unload_chunk")
            .put(net.minecraft.network.packet.s2c.play.GameJoinS2CPacket.class, "game_join")
            .put(net.minecraft.network.packet.s2c.play.InventoryS2CPacket.class, "inventory")
            .put(net.minecraft.network.packet.s2c.play.ParticleS2CPacket.class, "particle")
            .put(net.minecraft.network.packet.s2c.play.PlayerListS2CPacket.class, "player_list")
            .put(net.minecraft.network.packet.c2s.play.UpdateSelectedSlotC2SPacket.class, "update_selected_slot")
            .put(net.minecraft.network.packet.s2c.login.LoginDisconnectS2CPacket.class, "login_disconnect")
            .put(net.minecraft.network.packet.s2c.play.DifficultyS2CPacket.class, "difficulty")
            .put(net.minecraft.network.packet.s2c.play.LightUpdateS2CPacket.class, "light_update")
            .put(net.minecraft.network.packet.s2c.login.LoginQueryRequestS2CPacket.class, "login_query_request")
            .put(net.minecraft.network.packet.c2s.play.GuiCloseC2SPacket.class, "gui_close")
            .put(net.minecraft.network.packet.s2c.play.CommandTreeS2CPacket.class, "command_tree")
            .put(net.minecraft.network.packet.s2c.play.ChunkDeltaUpdateS2CPacket.class, "chunk_delta_update")
            .put(net.minecraft.network.packet.c2s.play.QueryBlockNbtC2SPacket.class, "query_block_nbt")
            .put(net.minecraft.network.packet.c2s.play.CreativeInventoryActionC2SPacket.class,
                    "creative_inventory_action")
            .put(net.minecraft.network.packet.s2c.play.LookAtS2CPacket.class, "look_at")
            .put(net.minecraft.network.packet.s2c.play.BlockEntityUpdateS2CPacket.class, "block_entity_update")
            .put(net.minecraft.network.packet.s2c.play.CloseScreenS2CPacket.class, "close_screen")
            .put(net.minecraft.network.packet.c2s.play.ClickWindowC2SPacket.class, "click_window")
            .put(net.minecraft.network.packet.c2s.play.ChatMessageC2SPacket.class, "chat_message")
            .put(net.minecraft.network.packet.s2c.play.EntityS2CPacket.RotateAndMoveRelative.class,
                    "entity_rotate_and_move_relative")
            .put(net.minecraft.network.packet.s2c.play.DisconnectS2CPacket.class, "disconnect")
            .put(net.minecraft.network.packet.c2s.play.TeleportConfirmC2SPacket.class, "teleport_confirm")
            .put(net.minecraft.network.packet.c2s.play.CustomPayloadC2SPacket.class, "custom_payload")
            .put(net.minecraft.network.packet.s2c.play.PlayerRespawnS2CPacket.class, "player_respawn")
            .put(net.minecraft.network.packet.s2c.play.WorldEventS2CPacket.class, "world_event")
            .put(net.minecraft.network.packet.s2c.play.SynchronizeTagsS2CPacket.class, "synchronize_tags")
            .put(net.minecraft.network.packet.c2s.play.RecipeBookDataC2SPacket.class, "recipe_book_data")
            .put(net.minecraft.network.packet.s2c.play.ScreenHandlerSlotUpdateS2CPacket.class,
                    "screen_handler_slot_update")
            .put(net.minecraft.network.packet.s2c.play.EntityStatusEffectS2CPacket.class, "entity_status_effect")
            .put(net.minecraft.network.packet.c2s.play.SelectVillagerTradeC2SPacket.class, "select_villager_trade")
            .put(net.minecraft.network.packet.c2s.play.BookUpdateC2SPacket.class, "book_update")
            .put(net.minecraft.network.packet.c2s.play.RenameItemC2SPacket.class, "rename_item")
            .put(net.minecraft.network.packet.s2c.play.SetCameraEntityS2CPacket.class, "set_camera_entity")
            .put(net.minecraft.network.packet.s2c.play.ExplosionS2CPacket.class, "explosion")
            .put(net.minecraft.network.packet.s2c.play.TitleS2CPacket.class, "title")
            .put(net.minecraft.network.packet.c2s.play.CraftRequestC2SPacket.class, "craft_request")
            .put(net.minecraft.network.packet.c2s.play.UpdateDifficultyC2SPacket.class, "update_difficulty")
            .put(net.minecraft.network.packet.s2c.login.LoginSuccessS2CPacket.class, "login_success")
            .put(net.minecraft.network.packet.s2c.play.EntityAttachS2CPacket.class, "entity_attach")
            .put(net.minecraft.network.packet.s2c.play.BlockUpdateS2CPacket.class, "block_update")
            .put(net.minecraft.network.packet.c2s.play.ButtonClickC2SPacket.class, "button_click")
            .put(net.minecraft.network.packet.s2c.play.KeepAliveS2CPacket.class, "keep_alive")
            .put(net.minecraft.network.packet.s2c.play.CooldownUpdateS2CPacket.class, "cooldown_update")
            .put(net.minecraft.network.packet.s2c.play.ExperienceOrbSpawnS2CPacket.class, "experience_orb_spawn")
            .put(net.minecraft.network.packet.c2s.login.LoginQueryResponseC2SPacket.class, "login_query_response")
            .put(net.minecraft.network.packet.c2s.play.PlayerActionC2SPacket.class, "player_action")
            .put(net.minecraft.network.packet.s2c.play.UnlockRecipesS2CPacket.class, "unlock_recipes")
            .put(net.minecraft.network.packet.s2c.play.EntityPassengersSetS2CPacket.class, "entity_passengers_set")
            .put(net.minecraft.network.packet.s2c.play.EntitySetHeadYawS2CPacket.class, "entity_set_head_yaw")
            .put(net.minecraft.network.packet.s2c.play.CommandSuggestionsS2CPacket.class, "command_suggestions")
            .put(net.minecraft.network.packet.s2c.play.PaintingSpawnS2CPacket.class, "painting_spawn")
            .put(net.minecraft.network.packet.s2c.play.StopSoundS2CPacket.class, "stop_sound")
            .put(net.minecraft.network.packet.c2s.query.QueryRequestC2SPacket.class, "query_request")
            .put(net.minecraft.network.packet.s2c.play.EntityAttributesS2CPacket.class, "entity_attributes")
            .put(net.minecraft.network.packet.c2s.play.PlayerInteractItemC2SPacket.class, "player_interact_item")
            .put(net.minecraft.network.packet.s2c.play.PlaySoundFromEntityS2CPacket.class, "play_sound_from_entity")
            .put(net.minecraft.network.packet.s2c.play.HeldItemChangeS2CPacket.class, "held_item_change")
            .put(net.minecraft.network.packet.s2c.play.EntityS2CPacket.class, "entity")
            .put(net.minecraft.network.packet.s2c.play.EntityS2CPacket.MoveRelative.class, "entity_move_relative")
            .put(net.minecraft.network.packet.c2s.play.UpdateSignC2SPacket.class, "update_sign")
            .put(net.minecraft.network.packet.s2c.play.EntitySpawnS2CPacket.class, "entity_spawn")
            .put(net.minecraft.network.packet.c2s.handshake.HandshakeC2SPacket.class, "handshake")
            .put(net.minecraft.network.packet.c2s.play.PlayerMoveC2SPacket.LookOnly.class, "player_move_look_only")
            .put(net.minecraft.network.packet.s2c.play.SignEditorOpenS2CPacket.class, "sign_editor_open")
            .put(net.minecraft.network.packet.s2c.play.EntitiesDestroyS2CPacket.class, "entities_destroy")
            .put(net.minecraft.network.packet.c2s.play.RequestCommandCompletionsC2SPacket.class,
                    "request_command_completions")
            .put(net.minecraft.network.packet.c2s.play.HandSwingC2SPacket.class, "hand_swing")
            .put(net.minecraft.network.packet.s2c.play.PlayerListHeaderS2CPacket.class, "player_list_header")
            .put(net.minecraft.network.packet.s2c.play.ScreenHandlerPropertyUpdateS2CPacket.class,
                    "screen_handler_property_update")
            .put(net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.class, "synchronize_recipes")
            .put(net.minecraft.network.packet.s2c.play.WorldBorderS2CPacket.class, "world_border")
            .put(net.minecraft.network.packet.s2c.play.ScoreboardObjectiveUpdateS2CPacket.class,
                    "scoreboard_objective_update")
            .put(net.minecraft.network.packet.c2s.play.ClientSettingsC2SPacket.class, "client_settings")
            .put(net.minecraft.network.packet.s2c.play.EntityPositionS2CPacket.class, "entity_position")
            .put(net.minecraft.network.packet.s2c.play.OpenHorseScreenS2CPacket.class, "open_horse_screen")
            .put(net.minecraft.network.packet.c2s.query.QueryPingC2SPacket.class, "query_ping")
            .put(net.minecraft.network.packet.c2s.play.ClientCommandC2SPacket.class, "client_command")
            .put(net.minecraft.network.packet.c2s.play.SpectatorTeleportC2SPacket.class, "spectator_teleport")
            .put(net.minecraft.network.packet.s2c.play.PlayerPositionLookS2CPacket.class, "player_position_look")
            .put(net.minecraft.network.packet.s2c.play.EntityS2CPacket.Rotate.class, "entity_rotate")
            .put(net.minecraft.network.packet.s2c.play.SetTradeOffersS2CPacket.class, "set_trade_offers")
            .put(net.minecraft.network.packet.c2s.play.UpdateDifficultyLockC2SPacket.class, "update_difficulty_lock")
            .put(net.minecraft.network.packet.s2c.play.CustomPayloadS2CPacket.class, "custom_payload")
            .put(net.minecraft.network.packet.s2c.play.ChunkDataS2CPacket.class, "chunk_data")
            .put(net.minecraft.network.packet.c2s.play.ResourcePackStatusC2SPacket.class, "resource_pack_status")
            .put(net.minecraft.network.packet.s2c.play.EntityStatusS2CPacket.class, "entity_status")
            .put(net.minecraft.network.packet.c2s.play.RecipeCategoryOptionsC2SPacket.class, "recipe_category_options")
            .put(net.minecraft.network.packet.s2c.play.MobSpawnS2CPacket.class, "mob_spawn")
            .put(net.minecraft.network.packet.s2c.play.StatisticsS2CPacket.class, "statistics")
            .put(net.minecraft.network.packet.s2c.play.ChunkRenderDistanceCenterS2CPacket.class,
                    "chunk_render_distance_center")
            .put(net.minecraft.network.packet.s2c.play.RemoveEntityStatusEffectS2CPacket.class,
                    "remove_entity_status_effect")
            .put(net.minecraft.network.packet.s2c.query.QueryPongS2CPacket.class, "query_pong")
            .put(net.minecraft.network.packet.s2c.query.QueryResponseS2CPacket.class, "query_response")
            .put(net.minecraft.network.packet.c2s.play.JigsawGeneratingC2SPacket.class, "jigsaw_generating")
            .put(net.minecraft.network.packet.s2c.play.ConfirmGuiActionS2CPacket.class, "confirm_gui_action")
            .put(net.minecraft.network.packet.s2c.play.PlayerSpawnPositionS2CPacket.class, "player_spawn_position")
            .put(net.minecraft.network.packet.s2c.play.ScoreboardDisplayS2CPacket.class, "scoreboard_display")
            .put(net.minecraft.network.packet.c2s.login.LoginKeyC2SPacket.class, "login_key")
            .put(net.minecraft.network.packet.s2c.login.LoginCompressionS2CPacket.class, "login_compression")
            .put(net.minecraft.network.packet.c2s.play.UpdateCommandBlockC2SPacket.class, "update_command_block")
            .put(net.minecraft.network.packet.c2s.play.BoatPaddleStateC2SPacket.class, "boat_paddle_state")
            .put(net.minecraft.network.packet.s2c.play.PlaySoundIdS2CPacket.class, "play_sound_id")
            .put(net.minecraft.network.packet.s2c.play.OpenScreenS2CPacket.class, "open_screen")
            .put(net.minecraft.network.packet.c2s.play.VehicleMoveC2SPacket.class, "vehicle_move")
            .put(net.minecraft.network.packet.s2c.play.SelectAdvancementTabS2CPacket.class, "select_advancement_tab")
            .put(net.minecraft.network.packet.s2c.play.EntityAnimationS2CPacket.class, "entity_animation")
            .put(net.minecraft.network.packet.s2c.play.CombatEventS2CPacket.class, "combat_event")
            .put(net.minecraft.network.packet.s2c.play.TeamS2CPacket.class, "team")
            .put(net.minecraft.network.packet.s2c.play.OpenWrittenBookS2CPacket.class, "open_written_book")
            .put(net.minecraft.network.packet.s2c.play.PlayerAbilitiesS2CPacket.class, "player_abilities")
            .put(net.minecraft.network.packet.s2c.play.EntityEquipmentUpdateS2CPacket.class, "entity_equipment_update")
            .put(net.minecraft.network.packet.s2c.play.MapUpdateS2CPacket.class, "map_update")
            .put(net.minecraft.network.packet.s2c.play.GameStateChangeS2CPacket.class, "game_state_change")
            .put(net.minecraft.network.packet.c2s.play.UpdateJigsawC2SPacket.class, "update_jigsaw")
            .put(net.minecraft.network.packet.c2s.play.PlayerMoveC2SPacket.class, "player_move")
            .put(net.minecraft.network.packet.s2c.play.EntityVelocityUpdateS2CPacket.class, "entity_velocity_update")
            .put(net.minecraft.network.packet.c2s.play.ClientStatusC2SPacket.class, "client_status")
            .put(net.minecraft.network.packet.s2c.play.ResourcePackSendS2CPacket.class, "resource_pack_send")
            .put(net.minecraft.network.packet.c2s.play.UpdateBeaconC2SPacket.class, "update_beacon")
            .put(net.minecraft.network.packet.s2c.play.BossBarS2CPacket.class, "boss_bar")
            .put(net.minecraft.network.packet.s2c.login.LoginHelloS2CPacket.class, "login_hello")
            .put(net.minecraft.network.packet.c2s.play.UpdateStructureBlockC2SPacket.class, "update_structure_block")
            .put(net.minecraft.network.packet.s2c.play.BlockEventS2CPacket.class, "block_event")
            .put(net.minecraft.network.packet.c2s.play.PlayerMoveC2SPacket.Both.class, "player_move_both")
            .put(net.minecraft.network.packet.s2c.play.WorldTimeUpdateS2CPacket.class, "world_time_update")
            .put(net.minecraft.network.packet.s2c.play.VehicleMoveS2CPacket.class, "vehicle_move")
            .put(net.minecraft.network.packet.c2s.play.PlayerInputC2SPacket.class, "player_input")
            .put(net.minecraft.network.packet.s2c.play.CraftFailedResponseS2CPacket.class, "craft_failed_response")
            .put(net.minecraft.network.packet.c2s.play.ConfirmGuiActionC2SPacket.class, "confirm_gui_action")
            .put(net.minecraft.network.packet.s2c.play.GameMessageS2CPacket.class, "game_message")
            .put(net.minecraft.network.packet.s2c.play.ItemPickupAnimationS2CPacket.class, "item_pickup_animation")
            .put(net.minecraft.network.packet.s2c.play.HealthUpdateS2CPacket.class, "health_update")
            .put(net.minecraft.network.packet.s2c.play.PlayerSpawnS2CPacket.class, "player_spawn")
            .put(net.minecraft.network.packet.c2s.play.PlayerInteractEntityC2SPacket.class, "player_interact_entity")
            .put(net.minecraft.network.packet.c2s.login.LoginHelloC2SPacket.class, "login_hello")
            .put(net.minecraft.network.packet.c2s.play.PlayerMoveC2SPacket.PositionOnly.class,
                    "player_move_position_only")
            .put(net.minecraft.network.packet.c2s.play.QueryEntityNbtC2SPacket.class, "query_entity_nbt")
            .put(net.minecraft.network.packet.c2s.play.PickFromInventoryC2SPacket.class, "pick_from_inventory")
            .put(net.minecraft.network.packet.c2s.play.UpdateCommandBlockMinecartC2SPacket.class,
                    "update_command_block_minecart")
            .put(net.minecraft.network.packet.s2c.play.PlaySoundS2CPacket.class, "play_sound")
            .put(net.minecraft.network.packet.s2c.play.AdvancementUpdateS2CPacket.class, "advancement_update")
            .put(net.minecraft.network.packet.s2c.play.ChunkLoadDistanceS2CPacket.class, "chunk_load_distance")
            .build();

    public static String getName(Class<?> packetClass) {
        return VANILLA_PACKET_NAMES.getOrDefault(packetClass, packetClass.getName());
    }

}
